### ISSUE TITLE
[Feature request] Light version for browsers which do not support themes

### ISSUE THREAD

**Issue by claell** [openhab/org.openhab.ui.habpanel#292]
Currently I am using an eBook Reader as an information display with HABPanel. The current white font on black background theme is a bit hard to read sometimes and I think this could be improved with using light theme.
Unfortunately the dropdown menu for selecting themes shows "Themes are not compatible with this browser".

Is there a way to still use a light theme? Or can you implement a way to use it?

**Comment by ghys** [comment]
Probably doable with an external CSS file referenced in the settings.
Since your browser doesn't support CSS variables, it's more complicated but still feasible with a few classes overrides:
```css
body, .container, .header, .dashboard-title, h2, .drawer, .menu li:not(.active) {
    background: white !important;
    color: black !important;
}

a {
    color: darkblue;
}

.box {
    background: lightgray !important;
    color: black !important;
}
```

Create a file in `html/light.css` in your config folder with the above and reference `/static/light.css` in the settings.
